//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDAdmin.BLL.AccountsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Counts {
            get {
                return this.CountsField;
            }
            set {
                if ((object.ReferenceEquals(this.CountsField, value) != true)) {
                    this.CountsField = value;
                    this.RaisePropertyChanged("Counts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedDateField, value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountListEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountListEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFIDAdmin.BLL.AccountsService.AccountEntityDC[] AccountListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public RFIDAdmin.BLL.AccountsService.AccountEntityDC[] AccountList {
            get {
                return this.AccountListField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountListField, value) != true)) {
                    this.AccountListField = value;
                    this.RaisePropertyChanged("AccountList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AffiliationEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AffiliationEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AffiliationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AffiliationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AffiliationID {
            get {
                return this.AffiliationIDField;
            }
            set {
                if ((this.AffiliationIDField.Equals(value) != true)) {
                    this.AffiliationIDField = value;
                    this.RaisePropertyChanged("AffiliationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AffiliationName {
            get {
                return this.AffiliationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AffiliationNameField, value) != true)) {
                    this.AffiliationNameField = value;
                    this.RaisePropertyChanged("AffiliationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DepartmentEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AffiliationListEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AffiliationListEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFIDAdmin.BLL.AccountsService.AffiliationEntityDC[] AffiliationListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public RFIDAdmin.BLL.AccountsService.AffiliationEntityDC[] AffiliationList {
            get {
                return this.AffiliationListField;
            }
            set {
                if ((object.ReferenceEquals(this.AffiliationListField, value) != true)) {
                    this.AffiliationListField = value;
                    this.RaisePropertyChanged("AffiliationList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentListEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DepartmentListEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFIDAdmin.BLL.AccountsService.DepartmentEntityDC[] DepartmentListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public RFIDAdmin.BLL.AccountsService.DepartmentEntityDC[] DepartmentList {
            get {
                return this.DepartmentListField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentListField, value) != true)) {
                    this.DepartmentListField = value;
                    this.RaisePropertyChanged("DepartmentList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountsService.AccountsServiceSoap")]
    public interface AccountsServiceSoap {
        
        // CODEGEN: Generating message contract since element name member from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAccount", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.SaveAccountResponse SaveAccount(RFIDAdmin.BLL.AccountsService.SaveAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveAccountResponse> SaveAccountAsync(RFIDAdmin.BLL.AccountsService.SaveAccountRequest request);
        
        // CODEGEN: Generating message contract since element name GetAccountByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountByID", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.GetAccountByIDResponse GetAccountByID(RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountByID", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAccountByIDResponse> GetAccountByIDAsync(RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest request);
        
        // CODEGEN: Generating message contract since element name Search from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAccountMemberCount", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponse GetAllAccountMemberCount(RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAccountMemberCount", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponse> GetAllAccountMemberCountAsync(RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest request);
        
        // CODEGEN: Generating message contract since element name Search from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAccount", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.GetAllAccountResponse GetAllAccount(RFIDAdmin.BLL.AccountsService.GetAllAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAccountResponse> GetAllAccountAsync(RFIDAdmin.BLL.AccountsService.GetAllAccountRequest request);
        
        // CODEGEN: Generating message contract since element name AffiliationEntityDC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAffilation", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.SaveAffilationResponse SaveAffilation(RFIDAdmin.BLL.AccountsService.SaveAffilationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAffilation", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveAffilationResponse> SaveAffilationAsync(RFIDAdmin.BLL.AccountsService.SaveAffilationRequest request);
        
        // CODEGEN: Generating message contract since element name DepartmentEntityDC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDepertment", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.SaveDepertmentResponse SaveDepertment(RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDepertment", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveDepertmentResponse> SaveDepertmentAsync(RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllAffiliationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAffiliation", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponse GetAllAffiliation(RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAffiliation", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponse> GetAllAffiliationAsync(RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllDepartmentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDepartment", ReplyAction="*")]
        RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponse GetAllDepartment(RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponse> GetAllDepartmentAsync(RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAccount", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.SaveAccountRequestBody Body;
        
        public SaveAccountRequest() {
        }
        
        public SaveAccountRequest(RFIDAdmin.BLL.AccountsService.SaveAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AccountEntityDC member;
        
        public SaveAccountRequestBody() {
        }
        
        public SaveAccountRequestBody(RFIDAdmin.BLL.AccountsService.AccountEntityDC member) {
            this.member = member;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.SaveAccountResponseBody Body;
        
        public SaveAccountResponse() {
        }
        
        public SaveAccountResponse(RFIDAdmin.BLL.AccountsService.SaveAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AccountEntityDC SaveAccountResult;
        
        public SaveAccountResponseBody() {
        }
        
        public SaveAccountResponseBody(RFIDAdmin.BLL.AccountsService.AccountEntityDC SaveAccountResult) {
            this.SaveAccountResult = SaveAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountByID", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAccountByIDRequestBody Body;
        
        public GetAccountByIDRequest() {
        }
        
        public GetAccountByIDRequest(RFIDAdmin.BLL.AccountsService.GetAccountByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid AccountID;
        
        public GetAccountByIDRequestBody() {
        }
        
        public GetAccountByIDRequestBody(System.Guid AccountID) {
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAccountByIDResponseBody Body;
        
        public GetAccountByIDResponse() {
        }
        
        public GetAccountByIDResponse(RFIDAdmin.BLL.AccountsService.GetAccountByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAccountByIDResult;
        
        public GetAccountByIDResponseBody() {
        }
        
        public GetAccountByIDResponseBody(RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAccountByIDResult) {
            this.GetAccountByIDResult = GetAccountByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAccountMemberCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAccountMemberCount", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequestBody Body;
        
        public GetAllAccountMemberCountRequest() {
        }
        
        public GetAllAccountMemberCountRequest(RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAccountMemberCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Search;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PageIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PageSize;
        
        public GetAllAccountMemberCountRequestBody() {
        }
        
        public GetAllAccountMemberCountRequestBody(string Search, int PageIndex, int PageSize) {
            this.Search = Search;
            this.PageIndex = PageIndex;
            this.PageSize = PageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAccountMemberCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAccountMemberCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponseBody Body;
        
        public GetAllAccountMemberCountResponse() {
        }
        
        public GetAllAccountMemberCountResponse(RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAccountMemberCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAllAccountMemberCountResult;
        
        public GetAllAccountMemberCountResponseBody() {
        }
        
        public GetAllAccountMemberCountResponseBody(RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAllAccountMemberCountResult) {
            this.GetAllAccountMemberCountResult = GetAllAccountMemberCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAccount", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllAccountRequestBody Body;
        
        public GetAllAccountRequest() {
        }
        
        public GetAllAccountRequest(RFIDAdmin.BLL.AccountsService.GetAllAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Search;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PageIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PageSize;
        
        public GetAllAccountRequestBody() {
        }
        
        public GetAllAccountRequestBody(string Search, int PageIndex, int PageSize) {
            this.Search = Search;
            this.PageIndex = PageIndex;
            this.PageSize = PageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllAccountResponseBody Body;
        
        public GetAllAccountResponse() {
        }
        
        public GetAllAccountResponse(RFIDAdmin.BLL.AccountsService.GetAllAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAllAccountResult;
        
        public GetAllAccountResponseBody() {
        }
        
        public GetAllAccountResponseBody(RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAllAccountResult) {
            this.GetAllAccountResult = GetAllAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAffilationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAffilation", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.SaveAffilationRequestBody Body;
        
        public SaveAffilationRequest() {
        }
        
        public SaveAffilationRequest(RFIDAdmin.BLL.AccountsService.SaveAffilationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAffilationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AffiliationEntityDC AffiliationEntityDC;
        
        public SaveAffilationRequestBody() {
        }
        
        public SaveAffilationRequestBody(RFIDAdmin.BLL.AccountsService.AffiliationEntityDC AffiliationEntityDC) {
            this.AffiliationEntityDC = AffiliationEntityDC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAffilationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAffilationResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.SaveAffilationResponseBody Body;
        
        public SaveAffilationResponse() {
        }
        
        public SaveAffilationResponse(RFIDAdmin.BLL.AccountsService.SaveAffilationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAffilationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AffiliationEntityDC SaveAffilationResult;
        
        public SaveAffilationResponseBody() {
        }
        
        public SaveAffilationResponseBody(RFIDAdmin.BLL.AccountsService.AffiliationEntityDC SaveAffilationResult) {
            this.SaveAffilationResult = SaveAffilationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDepertmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDepertment", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.SaveDepertmentRequestBody Body;
        
        public SaveDepertmentRequest() {
        }
        
        public SaveDepertmentRequest(RFIDAdmin.BLL.AccountsService.SaveDepertmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDepertmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.DepartmentEntityDC DepartmentEntityDC;
        
        public SaveDepertmentRequestBody() {
        }
        
        public SaveDepertmentRequestBody(RFIDAdmin.BLL.AccountsService.DepartmentEntityDC DepartmentEntityDC) {
            this.DepartmentEntityDC = DepartmentEntityDC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDepertmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDepertmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.SaveDepertmentResponseBody Body;
        
        public SaveDepertmentResponse() {
        }
        
        public SaveDepertmentResponse(RFIDAdmin.BLL.AccountsService.SaveDepertmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDepertmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.DepartmentEntityDC SaveDepertmentResult;
        
        public SaveDepertmentResponseBody() {
        }
        
        public SaveDepertmentResponseBody(RFIDAdmin.BLL.AccountsService.DepartmentEntityDC SaveDepertmentResult) {
            this.SaveDepertmentResult = SaveDepertmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAffiliationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAffiliation", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequestBody Body;
        
        public GetAllAffiliationRequest() {
        }
        
        public GetAllAffiliationRequest(RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllAffiliationRequestBody {
        
        public GetAllAffiliationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAffiliationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAffiliationResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponseBody Body;
        
        public GetAllAffiliationResponse() {
        }
        
        public GetAllAffiliationResponse(RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAffiliationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.AffiliationListEntityDC GetAllAffiliationResult;
        
        public GetAllAffiliationResponseBody() {
        }
        
        public GetAllAffiliationResponseBody(RFIDAdmin.BLL.AccountsService.AffiliationListEntityDC GetAllAffiliationResult) {
            this.GetAllAffiliationResult = GetAllAffiliationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDepartment", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequestBody Body;
        
        public GetAllDepartmentRequest() {
        }
        
        public GetAllDepartmentRequest(RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDepartmentRequestBody {
        
        public GetAllDepartmentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDepartmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponseBody Body;
        
        public GetAllDepartmentResponse() {
        }
        
        public GetAllDepartmentResponse(RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.AccountsService.DepartmentListEntityDC GetAllDepartmentResult;
        
        public GetAllDepartmentResponseBody() {
        }
        
        public GetAllDepartmentResponseBody(RFIDAdmin.BLL.AccountsService.DepartmentListEntityDC GetAllDepartmentResult) {
            this.GetAllDepartmentResult = GetAllDepartmentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountsServiceSoapChannel : RFIDAdmin.BLL.AccountsService.AccountsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountsServiceSoapClient : System.ServiceModel.ClientBase<RFIDAdmin.BLL.AccountsService.AccountsServiceSoap>, RFIDAdmin.BLL.AccountsService.AccountsServiceSoap {
        
        public AccountsServiceSoapClient() {
        }
        
        public AccountsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.SaveAccountResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.SaveAccount(RFIDAdmin.BLL.AccountsService.SaveAccountRequest request) {
            return base.Channel.SaveAccount(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.AccountEntityDC SaveAccount(RFIDAdmin.BLL.AccountsService.AccountEntityDC member) {
            RFIDAdmin.BLL.AccountsService.SaveAccountRequest inValue = new RFIDAdmin.BLL.AccountsService.SaveAccountRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.SaveAccountRequestBody();
            inValue.Body.member = member;
            RFIDAdmin.BLL.AccountsService.SaveAccountResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).SaveAccount(inValue);
            return retVal.Body.SaveAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveAccountResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.SaveAccountAsync(RFIDAdmin.BLL.AccountsService.SaveAccountRequest request) {
            return base.Channel.SaveAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveAccountResponse> SaveAccountAsync(RFIDAdmin.BLL.AccountsService.AccountEntityDC member) {
            RFIDAdmin.BLL.AccountsService.SaveAccountRequest inValue = new RFIDAdmin.BLL.AccountsService.SaveAccountRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.SaveAccountRequestBody();
            inValue.Body.member = member;
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).SaveAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.GetAccountByIDResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAccountByID(RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest request) {
            return base.Channel.GetAccountByID(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAccountByID(System.Guid AccountID) {
            RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAccountByIDRequestBody();
            inValue.Body.AccountID = AccountID;
            RFIDAdmin.BLL.AccountsService.GetAccountByIDResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAccountByID(inValue);
            return retVal.Body.GetAccountByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAccountByIDResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAccountByIDAsync(RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest request) {
            return base.Channel.GetAccountByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAccountByIDResponse> GetAccountByIDAsync(System.Guid AccountID) {
            RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAccountByIDRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAccountByIDRequestBody();
            inValue.Body.AccountID = AccountID;
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAccountByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllAccountMemberCount(RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest request) {
            return base.Channel.GetAllAccountMemberCount(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAllAccountMemberCount(string Search, int PageIndex, int PageSize) {
            RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequestBody();
            inValue.Body.Search = Search;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllAccountMemberCount(inValue);
            return retVal.Body.GetAllAccountMemberCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllAccountMemberCountAsync(RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest request) {
            return base.Channel.GetAllAccountMemberCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountResponse> GetAllAccountMemberCountAsync(string Search, int PageIndex, int PageSize) {
            RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllAccountMemberCountRequestBody();
            inValue.Body.Search = Search;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllAccountMemberCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.GetAllAccountResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllAccount(RFIDAdmin.BLL.AccountsService.GetAllAccountRequest request) {
            return base.Channel.GetAllAccount(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.AccountListEntityDC GetAllAccount(string Search, int PageIndex, int PageSize) {
            RFIDAdmin.BLL.AccountsService.GetAllAccountRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllAccountRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllAccountRequestBody();
            inValue.Body.Search = Search;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            RFIDAdmin.BLL.AccountsService.GetAllAccountResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllAccount(inValue);
            return retVal.Body.GetAllAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAccountResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllAccountAsync(RFIDAdmin.BLL.AccountsService.GetAllAccountRequest request) {
            return base.Channel.GetAllAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAccountResponse> GetAllAccountAsync(string Search, int PageIndex, int PageSize) {
            RFIDAdmin.BLL.AccountsService.GetAllAccountRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllAccountRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllAccountRequestBody();
            inValue.Body.Search = Search;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.SaveAffilationResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.SaveAffilation(RFIDAdmin.BLL.AccountsService.SaveAffilationRequest request) {
            return base.Channel.SaveAffilation(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.AffiliationEntityDC SaveAffilation(RFIDAdmin.BLL.AccountsService.AffiliationEntityDC AffiliationEntityDC) {
            RFIDAdmin.BLL.AccountsService.SaveAffilationRequest inValue = new RFIDAdmin.BLL.AccountsService.SaveAffilationRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.SaveAffilationRequestBody();
            inValue.Body.AffiliationEntityDC = AffiliationEntityDC;
            RFIDAdmin.BLL.AccountsService.SaveAffilationResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).SaveAffilation(inValue);
            return retVal.Body.SaveAffilationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveAffilationResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.SaveAffilationAsync(RFIDAdmin.BLL.AccountsService.SaveAffilationRequest request) {
            return base.Channel.SaveAffilationAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveAffilationResponse> SaveAffilationAsync(RFIDAdmin.BLL.AccountsService.AffiliationEntityDC AffiliationEntityDC) {
            RFIDAdmin.BLL.AccountsService.SaveAffilationRequest inValue = new RFIDAdmin.BLL.AccountsService.SaveAffilationRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.SaveAffilationRequestBody();
            inValue.Body.AffiliationEntityDC = AffiliationEntityDC;
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).SaveAffilationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.SaveDepertmentResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.SaveDepertment(RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest request) {
            return base.Channel.SaveDepertment(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.DepartmentEntityDC SaveDepertment(RFIDAdmin.BLL.AccountsService.DepartmentEntityDC DepartmentEntityDC) {
            RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest inValue = new RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.SaveDepertmentRequestBody();
            inValue.Body.DepartmentEntityDC = DepartmentEntityDC;
            RFIDAdmin.BLL.AccountsService.SaveDepertmentResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).SaveDepertment(inValue);
            return retVal.Body.SaveDepertmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveDepertmentResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.SaveDepertmentAsync(RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest request) {
            return base.Channel.SaveDepertmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.SaveDepertmentResponse> SaveDepertmentAsync(RFIDAdmin.BLL.AccountsService.DepartmentEntityDC DepartmentEntityDC) {
            RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest inValue = new RFIDAdmin.BLL.AccountsService.SaveDepertmentRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.SaveDepertmentRequestBody();
            inValue.Body.DepartmentEntityDC = DepartmentEntityDC;
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).SaveDepertmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllAffiliation(RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest request) {
            return base.Channel.GetAllAffiliation(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.AffiliationListEntityDC GetAllAffiliation() {
            RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequestBody();
            RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllAffiliation(inValue);
            return retVal.Body.GetAllAffiliationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllAffiliationAsync(RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest request) {
            return base.Channel.GetAllAffiliationAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllAffiliationResponse> GetAllAffiliationAsync() {
            RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllAffiliationRequestBody();
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllAffiliationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponse RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllDepartment(RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest request) {
            return base.Channel.GetAllDepartment(request);
        }
        
        public RFIDAdmin.BLL.AccountsService.DepartmentListEntityDC GetAllDepartment() {
            RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequestBody();
            RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponse retVal = ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllDepartment(inValue);
            return retVal.Body.GetAllDepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponse> RFIDAdmin.BLL.AccountsService.AccountsServiceSoap.GetAllDepartmentAsync(RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest request) {
            return base.Channel.GetAllDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.AccountsService.GetAllDepartmentResponse> GetAllDepartmentAsync() {
            RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest inValue = new RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequest();
            inValue.Body = new RFIDAdmin.BLL.AccountsService.GetAllDepartmentRequestBody();
            return ((RFIDAdmin.BLL.AccountsService.AccountsServiceSoap)(this)).GetAllDepartmentAsync(inValue);
        }
    }
}
