//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDAdmin.BLL.GateTerminalsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GateTerminalEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GateTerminalEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid GateTerminalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GateTerminalNameField;
        
        private System.Guid AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        private bool IsActiveField;
        
        private int GateTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GateTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid GateTerminalID {
            get {
                return this.GateTerminalIDField;
            }
            set {
                if ((this.GateTerminalIDField.Equals(value) != true)) {
                    this.GateTerminalIDField = value;
                    this.RaisePropertyChanged("GateTerminalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GateTerminalName {
            get {
                return this.GateTerminalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GateTerminalNameField, value) != true)) {
                    this.GateTerminalNameField = value;
                    this.RaisePropertyChanged("GateTerminalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int GateTypeID {
            get {
                return this.GateTypeIDField;
            }
            set {
                if ((this.GateTypeIDField.Equals(value) != true)) {
                    this.GateTypeIDField = value;
                    this.RaisePropertyChanged("GateTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string GateTypeName {
            get {
                return this.GateTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GateTypeNameField, value) != true)) {
                    this.GateTypeNameField = value;
                    this.RaisePropertyChanged("GateTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedDateField, value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GateTerminalListEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GateTerminalListEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC[] GateTerminalListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC[] GateTerminalList {
            get {
                return this.GateTerminalListField;
            }
            set {
                if ((object.ReferenceEquals(this.GateTerminalListField, value) != true)) {
                    this.GateTerminalListField = value;
                    this.RaisePropertyChanged("GateTerminalList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GateTypeListEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GateTypeListEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFIDAdmin.BLL.GateTerminalsService.GateTypeEntityDC[] GateTypeListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public RFIDAdmin.BLL.GateTerminalsService.GateTypeEntityDC[] GateTypeList {
            get {
                return this.GateTypeListField;
            }
            set {
                if ((object.ReferenceEquals(this.GateTypeListField, value) != true)) {
                    this.GateTypeListField = value;
                    this.RaisePropertyChanged("GateTypeList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GateTypeEntityDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GateTypeEntityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int GateTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GateTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GateTypeID {
            get {
                return this.GateTypeIDField;
            }
            set {
                if ((this.GateTypeIDField.Equals(value) != true)) {
                    this.GateTypeIDField = value;
                    this.RaisePropertyChanged("GateTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GateTypeName {
            get {
                return this.GateTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GateTypeNameField, value) != true)) {
                    this.GateTypeNameField = value;
                    this.RaisePropertyChanged("GateTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GateTerminalsService.GateTerminalsServiceSoap")]
    public interface GateTerminalsServiceSoap {
        
        // CODEGEN: Generating message contract since element name member from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveGateTerminal", ReplyAction="*")]
        RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponse SaveGateTerminal(RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveGateTerminal", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponse> SaveGateTerminalAsync(RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGateTerminalByID", ReplyAction="*")]
        RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponse GetAllGateTerminalByID(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGateTerminalByID", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponse> GetAllGateTerminalByIDAsync(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllGateTypeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGateType", ReplyAction="*")]
        RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponse GetAllGateType(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGateType", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponse> GetAllGateTypeAsync(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGateTerminalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveGateTerminal", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequestBody Body;
        
        public SaveGateTerminalRequest() {
        }
        
        public SaveGateTerminalRequest(RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveGateTerminalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC member;
        
        public SaveGateTerminalRequestBody() {
        }
        
        public SaveGateTerminalRequestBody(RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC member) {
            this.member = member;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGateTerminalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveGateTerminalResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponseBody Body;
        
        public SaveGateTerminalResponse() {
        }
        
        public SaveGateTerminalResponse(RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveGateTerminalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC SaveGateTerminalResult;
        
        public SaveGateTerminalResponseBody() {
        }
        
        public SaveGateTerminalResponseBody(RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC SaveGateTerminalResult) {
            this.SaveGateTerminalResult = SaveGateTerminalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGateTerminalByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGateTerminalByID", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequestBody Body;
        
        public GetAllGateTerminalByIDRequest() {
        }
        
        public GetAllGateTerminalByIDRequest(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGateTerminalByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Search;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PageIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int PageSize;
        
        public GetAllGateTerminalByIDRequestBody() {
        }
        
        public GetAllGateTerminalByIDRequestBody(string AccountID, string Search, int PageIndex, int PageSize) {
            this.AccountID = AccountID;
            this.Search = Search;
            this.PageIndex = PageIndex;
            this.PageSize = PageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGateTerminalByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGateTerminalByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponseBody Body;
        
        public GetAllGateTerminalByIDResponse() {
        }
        
        public GetAllGateTerminalByIDResponse(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGateTerminalByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GateTerminalListEntityDC GetAllGateTerminalByIDResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public GetAllGateTerminalByIDResponseBody() {
        }
        
        public GetAllGateTerminalByIDResponseBody(RFIDAdmin.BLL.GateTerminalsService.GateTerminalListEntityDC GetAllGateTerminalByIDResult, int count) {
            this.GetAllGateTerminalByIDResult = GetAllGateTerminalByIDResult;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGateTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGateType", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequestBody Body;
        
        public GetAllGateTypeRequest() {
        }
        
        public GetAllGateTypeRequest(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGateTypeRequestBody {
        
        public GetAllGateTypeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGateTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGateTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponseBody Body;
        
        public GetAllGateTypeResponse() {
        }
        
        public GetAllGateTypeResponse(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGateTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RFIDAdmin.BLL.GateTerminalsService.GateTypeListEntityDC GetAllGateTypeResult;
        
        public GetAllGateTypeResponseBody() {
        }
        
        public GetAllGateTypeResponseBody(RFIDAdmin.BLL.GateTerminalsService.GateTypeListEntityDC GetAllGateTypeResult) {
            this.GetAllGateTypeResult = GetAllGateTypeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GateTerminalsServiceSoapChannel : RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GateTerminalsServiceSoapClient : System.ServiceModel.ClientBase<RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap>, RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap {
        
        public GateTerminalsServiceSoapClient() {
        }
        
        public GateTerminalsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GateTerminalsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateTerminalsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateTerminalsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponse RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap.SaveGateTerminal(RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest request) {
            return base.Channel.SaveGateTerminal(request);
        }
        
        public RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC SaveGateTerminal(RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC member) {
            RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest inValue = new RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest();
            inValue.Body = new RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequestBody();
            inValue.Body.member = member;
            RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponse retVal = ((RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap)(this)).SaveGateTerminal(inValue);
            return retVal.Body.SaveGateTerminalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponse> RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap.SaveGateTerminalAsync(RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest request) {
            return base.Channel.SaveGateTerminalAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalResponse> SaveGateTerminalAsync(RFIDAdmin.BLL.GateTerminalsService.GateTerminalEntityDC member) {
            RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest inValue = new RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequest();
            inValue.Body = new RFIDAdmin.BLL.GateTerminalsService.SaveGateTerminalRequestBody();
            inValue.Body.member = member;
            return ((RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap)(this)).SaveGateTerminalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponse RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap.GetAllGateTerminalByID(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest request) {
            return base.Channel.GetAllGateTerminalByID(request);
        }
        
        public RFIDAdmin.BLL.GateTerminalsService.GateTerminalListEntityDC GetAllGateTerminalByID(string AccountID, string Search, int PageIndex, int PageSize, out int count) {
            RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest inValue = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest();
            inValue.Body = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequestBody();
            inValue.Body.AccountID = AccountID;
            inValue.Body.Search = Search;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponse retVal = ((RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap)(this)).GetAllGateTerminalByID(inValue);
            count = retVal.Body.count;
            return retVal.Body.GetAllGateTerminalByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponse> RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap.GetAllGateTerminalByIDAsync(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest request) {
            return base.Channel.GetAllGateTerminalByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDResponse> GetAllGateTerminalByIDAsync(string AccountID, string Search, int PageIndex, int PageSize) {
            RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest inValue = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequest();
            inValue.Body = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTerminalByIDRequestBody();
            inValue.Body.AccountID = AccountID;
            inValue.Body.Search = Search;
            inValue.Body.PageIndex = PageIndex;
            inValue.Body.PageSize = PageSize;
            return ((RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap)(this)).GetAllGateTerminalByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponse RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap.GetAllGateType(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest request) {
            return base.Channel.GetAllGateType(request);
        }
        
        public RFIDAdmin.BLL.GateTerminalsService.GateTypeListEntityDC GetAllGateType() {
            RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest inValue = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest();
            inValue.Body = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequestBody();
            RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponse retVal = ((RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap)(this)).GetAllGateType(inValue);
            return retVal.Body.GetAllGateTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponse> RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap.GetAllGateTypeAsync(RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest request) {
            return base.Channel.GetAllGateTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeResponse> GetAllGateTypeAsync() {
            RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest inValue = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequest();
            inValue.Body = new RFIDAdmin.BLL.GateTerminalsService.GetAllGateTypeRequestBody();
            return ((RFIDAdmin.BLL.GateTerminalsService.GateTerminalsServiceSoap)(this)).GetAllGateTypeAsync(inValue);
        }
    }
}
