//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDAdmin.BLL.LogsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogsService.LogsServiceSoap")]
    public interface LogsServiceSoap {
        
        // CODEGEN: Generating message contract since message InsertRFIDLogsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRFIDLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RFIDAdmin.BLL.LogsService.InsertRFIDLogsResponse InsertRFIDLogs(RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRFIDLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.LogsService.InsertRFIDLogsResponse> InsertRFIDLogsAsync(RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogsByRFID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RFIDAdmin.BLL.LogsService.RFIDLogEntityDC GetLogsByRFID(string RFID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogsByRFID", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.LogsService.RFIDLogEntityDC> GetLogsByRFIDAsync(string RFID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudentLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RFIDAdmin.BLL.LogsService.GetAllStudentLogsResponse GetAllStudentLogs(RFIDAdmin.BLL.LogsService.GetAllStudentLogsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudentLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.LogsService.GetAllStudentLogsResponse> GetAllStudentLogsAsync(RFIDAdmin.BLL.LogsService.GetAllStudentLogsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentLogEntityDC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid memberIDField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string iDNumberField;
        
        private string affiliationField;
        
        private string departmentField;
        
        private string accountNameField;
        
        private string rFIDField;
        
        private string dateTimeStampField;
        
        private string logTypeField;
        
        private string gateTerminalNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MemberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
                this.RaisePropertyChanged("MemberID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
                this.RaisePropertyChanged("IDNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Affiliation {
            get {
                return this.affiliationField;
            }
            set {
                this.affiliationField = value;
                this.RaisePropertyChanged("Affiliation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RFID {
            get {
                return this.rFIDField;
            }
            set {
                this.rFIDField = value;
                this.RaisePropertyChanged("RFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DateTimeStamp {
            get {
                return this.dateTimeStampField;
            }
            set {
                this.dateTimeStampField = value;
                this.RaisePropertyChanged("DateTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LogType {
            get {
                return this.logTypeField;
            }
            set {
                this.logTypeField = value;
                this.RaisePropertyChanged("LogType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string GateTerminalName {
            get {
                return this.gateTerminalNameField;
            }
            set {
                this.gateTerminalNameField = value;
                this.RaisePropertyChanged("GateTerminalName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RFIDLogEntityDC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid rFIDLogIDField;
        
        private string rFIDField;
        
        private string dateTimeStampField;
        
        private System.Guid gateTerminalIDField;
        
        private string statusField;
        
        private string logTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid RFIDLogID {
            get {
                return this.rFIDLogIDField;
            }
            set {
                this.rFIDLogIDField = value;
                this.RaisePropertyChanged("RFIDLogID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RFID {
            get {
                return this.rFIDField;
            }
            set {
                this.rFIDField = value;
                this.RaisePropertyChanged("RFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DateTimeStamp {
            get {
                return this.dateTimeStampField;
            }
            set {
                this.dateTimeStampField = value;
                this.RaisePropertyChanged("DateTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid GateTerminalID {
            get {
                return this.gateTerminalIDField;
            }
            set {
                this.gateTerminalIDField = value;
                this.RaisePropertyChanged("GateTerminalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LogType {
            get {
                return this.logTypeField;
            }
            set {
                this.logTypeField = value;
                this.RaisePropertyChanged("LogType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertRFIDLogs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertRFIDLogsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RFIDAdmin.BLL.LogsService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.LogsService.RFIDLogEntityDC RFIDlog;
        
        public InsertRFIDLogsRequest() {
        }
        
        public InsertRFIDLogsRequest(RFIDAdmin.BLL.LogsService.AuthHeader AuthHeader, RFIDAdmin.BLL.LogsService.RFIDLogEntityDC RFIDlog) {
            this.AuthHeader = AuthHeader;
            this.RFIDlog = RFIDlog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertRFIDLogsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertRFIDLogsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.LogsService.RFIDLogEntityDC InsertRFIDLogsResult;
        
        public InsertRFIDLogsResponse() {
        }
        
        public InsertRFIDLogsResponse(RFIDAdmin.BLL.LogsService.RFIDLogEntityDC InsertRFIDLogsResult) {
            this.InsertRFIDLogsResult = InsertRFIDLogsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllStudentLogs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllStudentLogsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Search;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string AccountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string EndDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int PageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int PageSize;
        
        public GetAllStudentLogsRequest() {
        }
        
        public GetAllStudentLogsRequest(string Search, string AccountID, string StartDate, string EndDate, int PageIndex, int PageSize) {
            this.Search = Search;
            this.AccountID = AccountID;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
            this.PageIndex = PageIndex;
            this.PageSize = PageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllStudentLogsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllStudentLogsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RFIDAdmin.BLL.LogsService.StudentLogEntityDC[] GetAllStudentLogsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Count;
        
        public GetAllStudentLogsResponse() {
        }
        
        public GetAllStudentLogsResponse(RFIDAdmin.BLL.LogsService.StudentLogEntityDC[] GetAllStudentLogsResult, int Count) {
            this.GetAllStudentLogsResult = GetAllStudentLogsResult;
            this.Count = Count;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogsServiceSoapChannel : RFIDAdmin.BLL.LogsService.LogsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogsServiceSoapClient : System.ServiceModel.ClientBase<RFIDAdmin.BLL.LogsService.LogsServiceSoap>, RFIDAdmin.BLL.LogsService.LogsServiceSoap {
        
        public LogsServiceSoapClient() {
        }
        
        public LogsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.LogsService.InsertRFIDLogsResponse RFIDAdmin.BLL.LogsService.LogsServiceSoap.InsertRFIDLogs(RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest request) {
            return base.Channel.InsertRFIDLogs(request);
        }
        
        public RFIDAdmin.BLL.LogsService.RFIDLogEntityDC InsertRFIDLogs(RFIDAdmin.BLL.LogsService.AuthHeader AuthHeader, RFIDAdmin.BLL.LogsService.RFIDLogEntityDC RFIDlog) {
            RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest inValue = new RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RFIDlog = RFIDlog;
            RFIDAdmin.BLL.LogsService.InsertRFIDLogsResponse retVal = ((RFIDAdmin.BLL.LogsService.LogsServiceSoap)(this)).InsertRFIDLogs(inValue);
            return retVal.InsertRFIDLogsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFIDAdmin.BLL.LogsService.InsertRFIDLogsResponse> RFIDAdmin.BLL.LogsService.LogsServiceSoap.InsertRFIDLogsAsync(RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest request) {
            return base.Channel.InsertRFIDLogsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.LogsService.InsertRFIDLogsResponse> InsertRFIDLogsAsync(RFIDAdmin.BLL.LogsService.AuthHeader AuthHeader, RFIDAdmin.BLL.LogsService.RFIDLogEntityDC RFIDlog) {
            RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest inValue = new RFIDAdmin.BLL.LogsService.InsertRFIDLogsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RFIDlog = RFIDlog;
            return ((RFIDAdmin.BLL.LogsService.LogsServiceSoap)(this)).InsertRFIDLogsAsync(inValue);
        }
        
        public RFIDAdmin.BLL.LogsService.RFIDLogEntityDC GetLogsByRFID(string RFID) {
            return base.Channel.GetLogsByRFID(RFID);
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.LogsService.RFIDLogEntityDC> GetLogsByRFIDAsync(string RFID) {
            return base.Channel.GetLogsByRFIDAsync(RFID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFIDAdmin.BLL.LogsService.GetAllStudentLogsResponse RFIDAdmin.BLL.LogsService.LogsServiceSoap.GetAllStudentLogs(RFIDAdmin.BLL.LogsService.GetAllStudentLogsRequest request) {
            return base.Channel.GetAllStudentLogs(request);
        }
        
        public RFIDAdmin.BLL.LogsService.StudentLogEntityDC[] GetAllStudentLogs(string Search, string AccountID, string StartDate, string EndDate, int PageIndex, int PageSize, out int Count) {
            RFIDAdmin.BLL.LogsService.GetAllStudentLogsRequest inValue = new RFIDAdmin.BLL.LogsService.GetAllStudentLogsRequest();
            inValue.Search = Search;
            inValue.AccountID = AccountID;
            inValue.StartDate = StartDate;
            inValue.EndDate = EndDate;
            inValue.PageIndex = PageIndex;
            inValue.PageSize = PageSize;
            RFIDAdmin.BLL.LogsService.GetAllStudentLogsResponse retVal = ((RFIDAdmin.BLL.LogsService.LogsServiceSoap)(this)).GetAllStudentLogs(inValue);
            Count = retVal.Count;
            return retVal.GetAllStudentLogsResult;
        }
        
        public System.Threading.Tasks.Task<RFIDAdmin.BLL.LogsService.GetAllStudentLogsResponse> GetAllStudentLogsAsync(RFIDAdmin.BLL.LogsService.GetAllStudentLogsRequest request) {
            return base.Channel.GetAllStudentLogsAsync(request);
        }
    }
}
